apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logiflow-ingress
  namespace: logiflow
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: logiflow.local
      http:
        paths:
          - path: /api/ws
            pathType: Prefix
            backend:
              service:
                name: realtime-service
                port:
                  number: 5005
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: graphql-service
                port:
                  number: 5006
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
